# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julian Cheal
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "http://juliancheal.co.uk" # the base hostname & protocol for your site
baseurl: "/words" # the subpath of your site, e.g. /blog
sources:
    - _assets/images

# Social
email: hello@julian.cheal.co.uk
twitter_username: juliancheal
github_username:  juliancheal


# Plugins
gems: [mm-jekyll-prism, rouge, jekyll-watch, jekyll-assets, redcarpet]

# Build settings
markdown: kramdown
# markdown: redcarpet
input: GFM

permalink: /:categories/:title/

exclude: ["CNAME", "Rakefile", "README.md", "LICENSE", "Gemfile", "Gemfile.lock"]
